import pygame
# Control
lvl = 6
train = False
get_nn_inputs = True
max_alive_time = 7
load_weights = True
render_blocks = False
save_img = True

# Levels
lvls = []

lvl1 = ['                                                                      ', '                                                                      ', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'X                                                                    X', 'X                                                                    X', 'X                                                                    X', 'X                                                                   XX', 'X                                                                  XX ', 'XX                                                                XX  ', ' XX                                                               X   ', '  XX                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                              X   ',
        '   X                             T                                X   ', '   X                                                              X   ', '   X                      XXXXXXXXXXXXXXXX                        X   ', '   X                      X              X                        X   ', '   X                      XX            XX                        X   ', '   X                       XXXXXXXXXXXXXX                         X   ', '   X                                                              X   ', '   X                                                              X   ', '   X                                                  XXXXXXXXXXXXX   ', '   X                                                  X               ', '   X                                                  X               ', '   X                                                  X               ', '   X                                                  X               ', '   X                                                  X               ', '   X   P            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               ', '   X               XX                                                 ', '   XXXXXXXXXXXXXXXXX                                                  ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ']

lvl2 = ['                                                                      ', '                                                                      ', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  ', 'X                                                  X                  ', 'X                                                  XXXX               ', 'X                                                  XXXXXXX            ', 'X                                                        XX           ', 'X                                                         XX          ', 'X                                                          XX         ', 'X                                                           X         ', 'X                                                           X         ', 'X                                                           X         ', 'X                                                           X         ', 'X                               T                           X         ', 'X                                                           X         ', 'X                             XXXXXXXXXXXXXXXXXXX           X         ', 'X                             X                 XX          X         ', 'X                             X                  X          X         ', 'X                             X                  X          X         ', 'X                             XX                 X          X         ', 'X                              XX                X          X         ', 'X                               XX               X          X         ', 'X                                X               X          X         ',
        'X                                X               X          X         ', 'X                                X               X          X         ', 'X                                X               X          X         ', 'X                                X               X          X         ', 'X                                X               X          X         ', 'X                                XX              X          X         ', 'X                                X               X          X         ', 'X                                XX             XX          X         ', 'X                                 XXXXXXXXXXXXXXX           X         ', 'X                                                           X         ', 'X                                                           X         ', 'XXXX                                                        X         ', '   XX                                                       X         ', '    XXXXX                                                   X         ', '       XX                                                   X         ', '       XX   P                                              XX         ', '       XX                                                 XX          ', '       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ']

lvl3 = ['                                                                      ', '                                                                      ', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'X                                                                    X', 'X                                                                    X', 'X                                                                    X', 'X        XXXXXX                                        XXXX          X', 'X       XX   XXDDD                                     XXXXX         X', 'X      XX    X   DD                                 DDD  X XXXX      X', 'X      X    XX    DD                               DD    X    XX     X', 'X     XX    X      D                               D     X     X     X', 'X     X     X      D                               D     X     X     X', 'X    XX     X      D                               D     X     X     X', 'X    X      X      D                               D     X     X     X', 'X   XX      X     DD                               DD    X     X     X', 'X   X       X    DD                                 D    X     XXXXX X', 'X  XX       XX   D                                  D    X         XXX', 'X  X         XXXXX                                  XXXXXX          XX', 'X  X             X                                  X                 ', 'X XX             X                                  X                 ', 'XXX              X                                  X                 ', '                 X                                  X                 ', '                 X                                  X                 ',
        '                 X                                  X                 ', '                XX                                  X                 ', '                XX                                  XX                ', '            XXXXX                                    XXXXX            ', '          XX                                             XXX          ', '          X                                                X          ', '          X                                                X          ', '          X                                                X          ', '          X                                                X          ', '          X                                                X          ', '          X                                                X          ', '          X                                                X          ', '          X                                                X          ', '          X    P                                       T   X          ', '          X                                                X          ', '          XXXXXXXXXXXX                          XXXXXXXXXXXX          ', '                     X                          X                     ', '                    XX                          XX                    ', '                    X                            X                    ', '                    X                            X                    ', '                    X                            X                    ', '                    X                            X                    ', '                    X                            X                    ']

lvl4 = ['                                                                      ',
        '                         XXXXXXXXXXXXXXXXXXX                          ',
        '                         X                 X                          ',
        '                         X                 X                          ',
        '                         X                 X                          ',
        '                         X         T       X                          ',
        '                         X     XXXXXXX     X                          ',
        '                         X     XXXXXXX     X                          ',
        '                         X                 X                          ',
        '                         X                 X                          ',
        '                         X                 X                          ',
        '                         X        XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XX   X                          ',
        '                         X    XX  XX  XXXXXX                          ',
        '                         X    XX  XX  XXXXXX                          ',
        '                         X                 X                          ',
        '                         X                 X                          ',
        '                         X   XXXXXXXXXXXXXXX                          ',
        '                         X   X                                        ',
        '                         X   X                                        ',
        '                         X   X XXXXXXXXXXXXXX                         ',
        '                         X   X X            X                         ',
        '                         X   X X            X                         ',
        '                         X   X X            X                         ',
        '                         X   XXX  XXXXXXX   X                         ',
        '                         X        X     X   X                         ',
        '                         X        X     X   X                         ',
        '                         X        X     X   X                         ',
        '                         XXXXXXXXXX     X   X                         ',
        '                           XXXXXXXXXXXXXX   X                         ',
        '                          XX                X                         ',
        '                          XX P              X                         ',
        '                          XX                X                         ',
        '                          XXXXXXXXXXXXXXXXXXX                         ']

lvl5 = ['                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX                         ', '                X                           XX                        ', '                X                            X                        ', '                X                            X                        ', '                X                          T X                        ', '                X                            X                        ', '                X                         XXXX                        ', '                X                      XXXX                           ', '                X                     XX                              ', '                X                     X                               ', '                X           XXXX      X                               ', '                X           X         X                               ', '                X           X         X                               ', '                X           XXXX      X                               ', '                X           X  X      X                               ', '                X           XX X      X                               ', '                X            X X      X                               ', '                X            XXX      X                               ', '                X              X      X                               ', '                X                     X                               ', '                X                     X                               ', '                X                     X                               ', '                X                     X                               ',
        '                X                     XXXXXXXX                        ', '                X                            X                        ', '                X                            X                        ', '                X                            X                        ', '                X                  XXXXXXX   X                        ', '                X                     X  X   X                        ', '                X                     XX X   X                        ', '                X                      XXX   X                        ', '                X                            X                        ', '                X                            X                        ', '                X                            X                        ', '                X                            X                        ', '                X                            X                        ', '                X                            X                        ', '                XX                           X                        ', '                 XX                          X                        ', '                  X                          X                        ', '                  X                          X                        ', '                  XXXX                       X                        ', '                     XXXXXX                  X                        ', '                       X P                   X                        ', '                       X                     X                        ', '                       XXXXXXXXXXXXXXXXXXXXXXX                        ']

lvl6 = ['                                                                      ', '                                                                      ', '                                                                      ', '                       XXXXXXXXXXXXXXXXXXXXXXXXXX                     ', '                      XX                        X                     ', '                     XX                         X                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X           DDDDD          X                     ', '                     X          DD   DD         X                     ', '                     X  T       D     D         X                     ', '                     XX         D     D         X                     ', '                      XXXXXXXXXXXXXXXXXXX       X                     ', '                                        X       X                     ', '                                       XX       X                     ', '                                      XX        X                     ', '                     XXXXXXXXXXXXXXXXXX         X                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X                     DDD  X                     ', '                     X                     D D  X                     ',
        '                     X        XXXXXXXXXXXXXXXXXXX                     ', '                     X        XX                                      ', '                     X         XXXXXXXXXXXXXXXXXX                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X              DDD         X                     ', '                     X             D  D         X                     ', '                     XXXXXXXXXXXXXXXXXXXX       X                     ', '                                       XX       X                     ', '                       XXXXXXXXXXXXXXXXX        X                     ', '                      XX                        X                     ', '                     XX                         X                     ', '                     X                          X                     ', '                     X                          X                     ', '                     X  P                       X                     ', '                     X                         XX                     ', '                     XXXXXXXXXXXXXXXXXXXXXXXXXXX                      ', '                                                                      ', '                                                                      ']

lvl7 = ['  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ', '  X                                                                X  ', '  X                                                                X  ', '  X                                                                X  ', '  X                                                                X  ', '  X                                                                X  ', '  X                                                                X  ', '  X                                                                X  ', '  X                                                            T   X  ', '  X                                                                X  ', '  X                                        XXXXX             XXXXXXX  ', '  X                                       XX   X             X        ', '  X                                      XX    X             X        ', '  X                   DDXXXXXXXXXXXXXXXXXX     X             X        ', '  X                  D                         X             X        ', '  X                  D                         X             X        ', '  X                  D                         X             X        ', '  X                  X    XXXXXXXXXXXXXXXXX    X             X        ', '  X                  X   XX               XX  XX             X        ', '  X                  X   X                 X  X             XX        ', '  X                  X   X                 X  X          XXXX         ', '  X                  X   X                 X  X          X            ', '  X                  X   X                 X  X          X            ',
        '  X                  X   X                 X  X       DDDX            ', '  X                  X   X                 X  X      DD  X            ', '  X                  X   X       XXX       X  X      D   X            ', '  X                  X   X     DDX XX      X  X      D   X            ', '  X                  X   X    D  X  XX     X  X      D   X            ', '  X                  X   X    D  X   X     X  X      D   X            ', '  X                  X   X    D  X   X     X  X       XXXX            ', '  X                  X   X    D  X   X     X  X       X               ', '  X                  X   X    D  X   X     X  X       X               ', '  X                  X   X     DDX   X     X  X       X               ', '  X                  X   X       X   X     X XX       X               ', '  X                  X   X       X   X     XXX        X               ', '  X                  X   X       X   X     XX         X               ', '  X                  X   X       X   X                X               ', '  X                  X  XX       X   X                X               ', '  X                  XXXX        X   X                X               ', '  X                              X   X                X               ', '  X                              X   X                X               ', '   X                             X   X                X               ', '   XX                           XX   XX              XX               ', '    X     P                    X      XXXXXXXXXXXXXXXX                ', '    X                         XX                                      ', '    XXXXXXXXXXXXXXXXXXXXXXXXXXXX                                      ']

lvl8 = ['                                                                      ', '                                                                      ', '                                                                      ', '           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ', '           X                                              X           ', '            X                                            X            ', '             X                                           X            ', '             X                                           X            ', '             X                                           X            ', '          XXXX                                           XXX          ', '          X                                                X          ', '          X                                                X          ', '       XXXX                                                XXXXX      ', '      XX                                                       X      ', '   XXXX                                                        XXXXX  ', '  XX                                                               XX ', ' XX                            XXXXXXXXX                            X ', ' X                             X       X                            X ', ' X                             X       X                            X ', ' X                             X       X                            X ', ' X                             X       X                            X ', ' X                             X       X                            X ', ' X                             X       X                            X ',
        ' X                             X       X                            X ', ' X                             X       X                            X ', ' X                             X       X                            X ', ' X                             X       X                            X ', ' X                             X       X                            X ', ' X   P                         X       X                         T  X ', ' X                             X       X                            X ', ' XXXXXX                        X       X                        XXXXX ', '  XXXXX                        X       X                        XXXXX ', ' XX  DD                        XX     XX                      DDDD  X ', ' X  D  DD DDD  DDD DDD   DD  DD X     XDD  DDD      DDDD  DD  D   D X ', ' XXD     D   DD   D   DDD  DD DD         D D  DDDDDDD   DD  DD     XX ', '                                          D                           ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ', '                                                                      ']

lvls.append(lvl1)  # Done
lvls.append(lvl2)  # Done
lvls.append(lvl3)  # Done
lvls.append(lvl4)  # Done
lvls.append(lvl5)  # Done
lvls.append(lvl6)  # Done
lvls.append(lvl7)  # Done
lvls.append(lvl8)  # Done

# Display
tile_size_x = 10
tile_size_y = 10
screen_width = 700
screen_height = 468

# Change for every map
level_map = lvls[lvl-1]
output_format = "jpg" if lvl not in [1, 2, 3] else "jpeg"
level_bg = pygame.image.load(f"./level_editor/lvl{lvl}.{output_format}")
scale_factor = 0.35 if lvl in [1, 2, 3, 6, 7, 8] else 0.2
jump_speed = -9 if lvl in [5, 7] else -10

# Nnet
GEN_SIZE = 170
generation_size = GEN_SIZE if train else 1
N_INPUT, N_HIDDEN, N_OUTPUT = 3, 10, 2
MUTATION_WEIGHT_MODIFY_CHANCE = 0.2
MUTATION_ARRAY_MIX_PERC = 0.5
MUTATION_CUT_OFF = 0.4
MUTATION_BAD_TO_KEEP = 0.2
MUTATION_MODIFY_CHANCE_LIMIT = 0.2
